name: Java Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:
# Sample push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Get Triggering User Name
      run: |
        echo "Triggered by: $GITHUB_ACTOR"

    - name: get email
      id: test
      uses: evvanErb/get-github-email-by-username-action@v1.25
      with:
          github-username: '$GITHUB_ACTOR' 
          
    - name: Print the found email
      run: echo "The email is ${{ steps.test.outputs.email }}"


    - name: Build with Maven
      run: mvn -B package --file calc/pom.xml
