name: Print Name

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  print_name:
    name: Print Name
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello
        run: echo "Hello Baquir"
